name: Reshab VirtuTeams Sign-In
on:
  schedule:
    # Runs every weekday (Monday-Friday) and Saturday at 9:15 AM IST (3:45 AM UTC)
    - cron: '45 3 * * 1-6'
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  signin:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set timeout to prevent hanging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
          
      - name: Run Reshab Sign-In
        run: |
          echo "🕐 Starting Reshab's VirtuTeams automation at $(TZ='Asia/Kolkata' date)"
          python3 reshab_virtueteams.py
          echo "✅ Reshab's automation completed at $(TZ='Asia/Kolkata' date)"
        
      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reshab-screenshots
          path: |
            *.png
          retention-days: 7
