name: Test Schedule
on:
  schedule:
    # Test: Run every 5 minutes for testing
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Schedule
        run: |
          echo "Schedule test at $(date)"
          echo "Current time: $(date -u)"
          echo "IST time: $(TZ='Asia/Kolkata' date)"
          echo "Schedule is working!"
