name: VirtuTeams Auto Sign-In
on:
  schedule:
    # Runs every weekday (Monday-Friday) at 9:50 AM IST (4:20 AM UTC)
    # Also runs at 9:55 AM IST (4:25 AM UTC) as backup
    - cron: '20 4 * * 1-5'
    - cron: '25 4 * * 1-5'
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  signin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
          
      - name: Run VirtuTeams Sign-In
        run: python3 virtueteams_signin.py
        
      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: virtueteams-screenshots
          path: |
            *.png
          retention-days: 7
